"""ZERO end-effector control node: SE(3) targets -> joint commands, for any embodiment.

    ros2 run zero_control eef_control --ros-args -p robot:=rebot
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pinocchio as pin
import rclpy
from ament_index_python.packages import get_package_share_directory
from rclpy.node import Node
from sensor_msgs.msg import JointState
from std_msgs.msg import Float64MultiArray

from zero_control.action import DIM, SIDES, pack, unpack
from zero_control.ik import ArmIK


class EefControlNode(Node):
    def __init__(self) -> None:
        super().__init__("zero_eef_control")
        # Everything robot-specific arrives as parameters, generated from zero_layout.ROBOTS by
        # scripts/gen_bringup.py into config/<robot>_control.yaml. The node imports nothing from the repo,
        # so it behaves identically from source or from an install tree, and zero_layout stays the single
        # source of truth.
        self.declare_parameter("robot", "rebot")
        self.declare_parameter("rate_hz", 100.0)
        self.declare_parameter("damping", 0.05)
        self.declare_parameter("gain", 1.0)
        self.declare_parameter("dq_max", 0.05)
        self.declare_parameter("eef_offset", [0.0, 0.0, 0.0])
        self.declare_parameter("eef_quat", [1.0, 0.0, 0.0, 0.0])
        self.declare_parameter("grip_range", [0.0, 0.04])
        self.declare_parameter("grip_ctrl_n", 1)
        for side in SIDES:
            self.declare_parameter(f"{side}_arm_joints", [""])
            self.declare_parameter(f"{side}_grip_joints", [""])
            self.declare_parameter(f"{side}_eef_frame", "")
            self.declare_parameter(f"{side}_home", [0.0])

        key = self.get_parameter("robot").value
        urdf = str(Path(get_package_share_directory("zero_description"))
                   / "urdf" / f"zero_{key}.urdf")
        eef_offset = tuple(self.get_parameter("eef_offset").value)
        eef_quat = tuple(self.get_parameter("eef_quat").value)

        self.ik: dict[str, ArmIK] = {}
        self.arm_pub: dict[str, object] = {}
        self.grip_pub: dict[str, object] = {}
        self.arm_joints: dict[str, list[str]] = {}
        self.home: dict[str, np.ndarray] = {}
        for side in SIDES:
            jn = list(self.get_parameter(f"{side}_arm_joints").value)
            frame = self.get_parameter(f"{side}_eef_frame").value
            if not jn or not jn[0] or not frame:
                raise SystemExit(
                    f"missing params for {side}: pass config/{key}_control.yaml "
                    f"(generated by scripts/gen_bringup.py)")
            self.arm_joints[side] = jn
            self.home[side] = np.asarray(
                self.get_parameter(f"{side}_home").value, dtype=float)
            if len(self.home[side]) != len(jn):
                raise SystemExit(
                    f"{side}_home has {len(self.home[side])} values, expected {len(jn)}")
            self.ik[side] = ArmIK(
                urdf, frame, jn, eef_offset, eef_quat,
                damping=self.get_parameter("damping").value,
                gain=self.get_parameter("gain").value,
                dq_max=self.get_parameter("dq_max").value)
            self.arm_pub[side] = self.create_publisher(
                Float64MultiArray, f"/{side}_arm_controller/commands", 10)
            self.grip_pub[side] = self.create_publisher(
                Float64MultiArray, f"/{side}_gripper_controller/commands", 10)

        self.grip_ctrl_n = int(self.get_parameter("grip_ctrl_n").value)
        self.grip_lo, self.grip_hi = tuple(self.get_parameter("grip_range").value)

        self.q = np.zeros(self.ik["left"].model.nq)   # full-model config, kept in sync
        self.q_meas = np.zeros(self.ik["left"].model.nq)  # PURE measurement, for /zero/eef_state
        # qpos indices of the gripper joints, for reporting the measured aperture before any command has
        # arrived (see _publish_state). Named explicitly by the params rather than inferred as
        # "anything under this side's prefix that is not an arm joint": that heuristic held only for
        # a two-joint slide jaw. The Robotiq 2F-85 adds four passive four-bar joints, and averaging
        # those into the aperture reports a number that is not an aperture at all.
        model = self.ik["left"].model
        self.grip_qidx: dict[str, list[int]] = {}
        for side in SIDES:
            want = self.get_parameter(f"{side}_grip_joints").value or []
            self.grip_qidx[side] = [model.joints[jid].idx_q for jid in range(1, model.njoints)
                                    if model.names[jid] in set(want)]
        if not all(self.grip_qidx.values()):
            self.get_logger().warn(
                "gripper joints not found in the model; /zero/eef_state will report the jaw as "
                "fully open until the first command arrives")
        self.have_js = False
        self.target: np.ndarray | None = None

        self.create_subscription(JointState, "/joint_states", self._on_js, 10)
        self.create_subscription(Float64MultiArray, "/zero/eef_target", self._on_target, 10)
        self.status_pub = self.create_publisher(Float64MultiArray, "/zero/ik_status", 10)
        # The measured 20-dim observation, for consumers that must not duplicate the kinematics.
        # policy_node needs this: it runs under lerobot_env, whose numpy 2.x cannot load ROS's pinocchio
        # (built against numpy 1.x), so it cannot do its own FK. Publishing it here also keeps this node
        # the single source of FK truth rather than a second implementation that could drift from the one
        # the dataset was recorded with.
        self.state_pub = self.create_publisher(Float64MultiArray, "/zero/eef_state", 10)

        hz = float(self.get_parameter("rate_hz").value)
        self.timer = self.create_timer(1.0 / hz, self._tick)
        self.get_logger().info(
            f"robot={key}  urdf={Path(urdf).name}  nq={self.ik['left'].model.nq}  "
            f"eef={[self.get_parameter(f'{s}_eef_frame').value for s in SIDES]}  {hz:.0f} Hz")

    # ---------------------------------------------------------------- callbacks
    def _on_js(self, msg: JointState) -> None:
        """Mirror measured joint positions into the pinocchio configuration vector.

        Matching BY NAME, not by index: /joint_states ordering is whatever the broadcaster emits
        and is not guaranteed to match the URDF's joint order.
        """
        model = self.ik["left"].model
        for name, pos in zip(msg.name, msg.position):
            jid = model.getJointId(name)
            if jid < model.njoints:
                self.q[model.joints[jid].idx_q] = pos
                self.q_meas[model.joints[jid].idx_q] = pos
        self.have_js = True
        self._publish_state()

    def _on_target(self, msg: Float64MultiArray) -> None:
        if len(msg.data) != DIM:
            self.get_logger().warn(f"/zero/eef_target has {len(msg.data)} values, expected {DIM}")
            return
        self.target = np.asarray(msg.data, dtype=float)

    # ---------------------------------------------------------------- control loop
    def _tick(self) -> None:
        if not self.have_js:
            return
        if self.target is None:
            # Hold home, not the measurement (see the module docstring). Commanding the measured
            # configuration is a gravity creep with no equilibrium.
            for side in SIDES:
                self._publish_arm(side, self.home[side])
            return

        poses, grips = unpack(self.target)
        status: list[float] = []
        for side in SIDES:
            ik = self.ik[side]
            pos, R = poses[side]
            res = ik.step(self.q, pin.SE3(R, np.asarray(pos, dtype=float)))
            self.q[ik.qidx] = res.q[ik.qidx]
            self._publish_arm(side, res.q[ik.qidx])
            self._publish_grip(side, grips[side])
            status += [res.pos_err, res.rot_err, float(res.clamped)]
        self.status_pub.publish(Float64MultiArray(data=status))

    def _publish_state(self) -> None:
        """Publish the measured 20-dim observation, identical to record_node._measured_state.

        Poses are FK on the measured joints (self.q_meas, not self.q, which carries the servo's
        own IK result). Grip channels are the last commanded grip, not a sensor reading, because
        that is what the recorder stored and therefore what a policy trained against.
        """
        fk = {s: self.ik[s].fk(self.q_meas) for s in SIDES}      # once per side, at 100 Hz
        poses = {s: (fk[s].translation, fk[s].rotation) for s in SIDES}
        # Before the first command, report the measured aperture, not 0.0. Defaulting to 0.0 meant
        # "fully closed", and in the training set a closed gripper only ever co-occurs with the can
        # already held mid-episode. So the policy's first observation was arm-at-home + jaw-closed +
        # can-on-table, a combination absent from all 40k frames. Zeroing these two channels cuts the
        # predicted chunk travel by 4-16x (145 -> 32 mm on ep 4, 66 -> 4 mm on ep 33), which is what made
        # the deployed policy sit still.
        #
        # Once a target exists this reports the last commanded grip, which is what
        # record_node._measured_state stored and therefore what the policy trained against.
        grips = {}
        for s in SIDES:
            if self.target is not None:
                grips[s] = float(self.target[9 if s == "left" else 19])
            elif self.grip_qidx[s]:
                # Keep the SIGN of the span. grip_range is (value at closed, value at open) and
                # those are not always ascending: the reBot's slide joints run 0 closed to 0.05
                # open, the Robotiq 2F-85's knuckle runs 0.8 closed to 0.0 open. A max(span, 1e-9)
                # guard written for the ascending case collapses a descending span to 1e-9 and
                # pins this channel at 0.0, i.e. permanently "fully closed", which is the exact
                # out-of-distribution first observation this block exists to avoid.
                span = self.grip_hi - self.grip_lo
                if abs(span) < 1e-9:
                    span = 1e-9
                grips[s] = float(np.clip(
                    (np.mean(self.q_meas[self.grip_qidx[s]]) - self.grip_lo) / span, 0.0, 1.0))
            else:
                grips[s] = 1.0
        self.state_pub.publish(Float64MultiArray(
            data=[float(v) for v in pack(poses, grips)]))

    def _publish_arm(self, side: str, q_arm: np.ndarray) -> None:
        self.arm_pub[side].publish(Float64MultiArray(data=[float(v) for v in q_arm]))

    def _publish_grip(self, side: str, grip: float) -> None:
        # grip is normalised [0,1]; 0 = closed, 1 = open. One value per commanded gripper joint, which is
        # 2 on the reBot (two real actuators) and 1 on Panda (one actuator drives both fingers through an
        # <equality>).
        g = self.grip_lo + float(np.clip(grip, 0.0, 1.0)) * (self.grip_hi - self.grip_lo)
        self.grip_pub[side].publish(Float64MultiArray(data=[g] * self.grip_ctrl_n))


def main() -> None:
    rclpy.init()
    node = EefControlNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.try_shutdown()


if __name__ == "__main__":
    main()
