"""Generate controller YAML + launch file per embodiment.

    python scripts/gen_bringup.py rebot
    python scripts/gen_bringup.py panda
"""

from __future__ import annotations

import sys

import mujoco

import zero_layout as L

BRINGUP = L.PKG.parent / "zero_bringup"


def controllers_yaml(key: str) -> str:
    r = L.ROBOTS[key]
    lines = [
        f"# Generated by scripts/gen_bringup.py {key}. Edit the generator, not this file.",
        "#",
        "# Every joint here must also appear in the URDF <ros2_control> block and the MJCF.",
        "# scripts/check_parity.py asserts that; a mismatch does not error, the joint just",
        "# silently never moves.",
        "",
        "controller_manager:",
        "  ros__parameters:",
        "    update_rate: 100",
        "",
        "    joint_state_broadcaster:",
        "      type: joint_state_broadcaster/JointStateBroadcaster",
        "",
    ]
    names = []
    for side in L.SIDES:
        for kind in ("arm", "gripper"):
            n = f"{side}_{kind}_controller"
            names.append(n)
            lines += [f"    {n}:",
                      "      type: position_controllers/JointGroupPositionController", ""]
    # F/T broadcasters, one per fingertip sensor. The plugin exposes each wrench as six state
    # interfaces; nothing reaches a topic until a broadcaster reads them, so an F/T sensor present in
    # both descriptions still publishes nothing without this. Same by-name binding failure as the
    # cameras.
    for sensor_name, _ in L.ft_sensors(key):
        n = f"{sensor_name}_broadcaster"
        names.append(n)
        lines += [f"    {n}:",
                  "      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster", ""]
    for sensor_name, _ in L.ft_sensors(key):
        lines += [f"{sensor_name}_broadcaster:", "  ros__parameters:",
                  f"    sensor_name: {sensor_name}",
                  f"    frame_id: {sensor_name}_site",
                  f"    topic_name: {L.CAM_NS}/ft/{sensor_name}", ""]

    for side in L.SIDES:
        for kind, joints in (("arm", r["arm_ctrl_joints"]), ("gripper", r["grip_ctrl_joints"])):
            lines += [f"{side}_{kind}_controller:", "  ros__parameters:", "    joints:"]
            lines += [f"      - {L.prefixed(side, j)}" for j in joints]
            lines += ["    command_interfaces:", "      - position",
                      "    state_interfaces:", "      - position", "      - velocity", ""]
    return "\n".join(lines), names


LAUNCH = '''"""Bring up the ZERO {key} dual-arm workstation in MuJoCo under ros2_control.

Generated by scripts/gen_bringup.py {key}. Edit the generator, not this file.

Pipeline:
  1. robot_state_publisher puts the URDF on /robot_description. It goes through xacro, which is
     load-bearing: the URDF's `mujoco_model` param uses `$(find zero_description)/...`, and only
     xacro expands that into an absolute path. mujoco_ros2_control does not resolve package://
     and dies with "MuJoCo model file 'package://...' does not exist!".
  2. mujoco_ros2_control's own ros2_control_node (not controller_manager's) loads the MJCF named
     by that param and starts the sim.
  3. Controllers spawn once the node is up. joint_state_broadcaster goes first, or the position
     controllers activate with no state interfaces to read and immediately fault.

Cameras: {ncam} MJCF cameras are published because the URDF declares a matching <sensor> for
each ({cams}). View them in RViz on {ns}/<cam>/image_raw.

Run:  ros2 launch zero_bringup {key}.launch.py
"""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, OpaqueFunction, RegisterEventHandler
from launch.event_handlers import OnProcessStart
from launch.substitutions import LaunchConfiguration
from launch.substitutions import Command, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from launch_ros.substitutions import FindPackageShare
from pathlib import Path

CONTROLLERS = {controllers!r}
MJCF = {mjcf!r}
START_OVERRIDE = {start_override!r}
CAN_DEFAULT_XY = ({can_x!r}, {can_y!r})


def _write_start_override(context):
    """Write the start-position override from can_x / can_y / can_yaw.

    The can's pose lives in the MJCF's `home` keyframe, which is baked at generation time. Rather
    than regenerate the model to move it, this reads that keyframe, substitutes the can's
    free-joint block, and writes a `<key qpos=... ctrl=.../>` file, the format
    mujoco_ros2_control's `override_start_position_file` hardware parameter expects. The whole
    qpos vector is copied from the compiled model, so arms, gripper and tray keep exactly the
    pose they were solved for and only the can moves.

    z is not an argument on purpose: the can's resting height is a function of its geometry (base
    on the table), and letting it be set by hand invites a can floating or half-buried. It is
    taken from the keyframe.
    """
    import mujoco
    import numpy as np

    x = float(LaunchConfiguration("can_x").perform(context))
    y = float(LaunchConfiguration("can_y").perform(context))
    yaw = float(LaunchConfiguration("can_yaw").perform(context))

    m = mujoco.MjModel.from_xml_path(MJCF)
    kid = mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_KEY, "home")
    if kid < 0:
        raise RuntimeError(f"no 'home' keyframe in {{MJCF}}")
    qpos = np.array(m.key_qpos[kid], dtype=float)
    ctrl = np.array(m.key_ctrl[kid], dtype=float)

    bid = mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_BODY, "obj_root")
    jid = next((j for j in range(m.njnt)
                if m.jnt_type[j] == mujoco.mjtJoint.mjJNT_FREE and m.jnt_bodyid[j] == bid), -1)
    if jid < 0:
        raise RuntimeError("obj_root has no free joint, cannot move the can")
    adr = m.jnt_qposadr[jid]

    # Reject bad placements rather than let the can spawn off the table, where the episode is
    # unrecordable and the cause is invisible from the images.
    tg = mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_GEOM, "table_top")
    cx, cy = m.geom_pos[tg][0], m.geom_pos[tg][1]
    hx, hy = m.geom_size[tg][0], m.geom_size[tg][1]
    if not (cx - hx <= x <= cx + hx and cy - hy <= y <= cy + hy):
        raise RuntimeError(
            f"can_x={{x}} can_y={{y}} is off the table "
            f"(x in [{{cx - hx:.3f}}, {{cx + hx:.3f}}], y in [{{cy - hy:.3f}}, {{cy + hy:.3f}}])")

    qpos[adr + 0] = x
    qpos[adr + 1] = y
    qpos[adr + 3] = np.cos(yaw / 2.0)      # quat w
    qpos[adr + 4] = 0.0
    qpos[adr + 5] = 0.0
    qpos[adr + 6] = np.sin(yaw / 2.0)      # quat z

    out = Path(START_OVERRIDE)
    # chr(10)/chr(34) instead of escape sequences, and every brace doubled: this text is a .format()
    # template that becomes a Python file, so a backslash escape survives one round of interpretation
    # fewer than it looks like it should, and a single brace is read as a format placeholder (which
    # failed with KeyError: v and left the old file behind).
    nl = chr(10)
    q = chr(34)
    body = [
        "<key",
        "  qpos=" + q + " ".join(f"{{v:.6f}}" for v in qpos) + q,
        "  qvel=" + q + " ".join("0" for _ in range(m.nv)) + q,
        "  ctrl=" + q + " ".join(f"{{v:.6f}}" for v in ctrl) + q,
        "/>",
    ]
    out.write_text(nl.join(body) + nl)
    print(f"[zero] can at x={{x:.3f}} y={{y:.3f}} yaw={{yaw:.3f}} -> {{out}}")
    return []


def _preflight(context):
    """Refuse to start if a mujoco_ros2_control node is already up.

    Two controller_managers on one ROS graph is not a clean failure. Both advertise
    /controller_manager/load_controller, /configure_controller and /list_controllers, so each
    spawner request is answered by whichever responds first: one request lands on the old
    manager and the next on the new one. The output is ~200 lines of contradictions ("Controller
    already loaded, skipping load_controller" from the manager that has them, "no controller with
    this name exists" from the one that does not, a controller logging "configure successful"
    while its spawner reports "Failed to configure controller"), none of which mentions the
    actual problem and all of which point at the controller config.
    """
    import subprocess
    found = subprocess.run(["pgrep", "-f", "mujoco_ros2_control/ros2_control_node"],
                           capture_output=True, text=True).stdout.split()
    if found:
        pids = ' '.join(found)
        raise RuntimeError(
            'a mujoco_ros2_control node is ALREADY RUNNING (pid ' + pids + '). Two '
            'controller_managers on one ROS graph answer each other service calls, so '
            'every spawner fails with a misleading message. Stop it first:  kill ' + pids)
    return []


def generate_launch_description() -> LaunchDescription:
    desc = FindPackageShare("zero_description")
    bringup = FindPackageShare("zero_bringup")
    urdf = PathJoinSubstitution([desc, "urdf", "zero_{key}.urdf"])
    controllers = PathJoinSubstitution([bringup, "config", "{key}_controllers.yaml"])
    control_params = PathJoinSubstitution([bringup, "config", "{key}_control.yaml"])

    rsp = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        output="screen",
        parameters=[{{"robot_description":
                     ParameterValue(Command(["xacro ", urdf]), value_type=str)}}],
    )
    ctrl = Node(
        package="mujoco_ros2_control",
        executable="ros2_control_node",
        output="screen",
        parameters=[controllers],
    )
    spawners = [
        Node(package="controller_manager", executable="spawner",
             arguments=[n, "--controller-manager", "/controller_manager"], output="screen")
        for n in CONTROLLERS
    ]
    # SE(3) -> joint IK. Starts alongside the spawners; it holds the measured configuration until a
    # /zero/eef_target arrives, so ordering against the controllers does not matter.
    eef = Node(
        package="zero_control", executable="eef_control", output="screen",
        parameters=[control_params],
    )
    return LaunchDescription([
        DeclareLaunchArgument("can_x", default_value=str(CAN_DEFAULT_XY[0]),
                             description="can position along x, metres, table frame"),
        DeclareLaunchArgument("can_y", default_value=str(CAN_DEFAULT_XY[1]),
                             description="can position along y, metres, table frame"),
        DeclareLaunchArgument("can_yaw", default_value="0.0",
                             description="can yaw, radians"),
        OpaqueFunction(function=_preflight),
        # Must run before the sim: the override file is read once, at hardware init.
        OpaqueFunction(function=_write_start_override),
        rsp, ctrl,
        RegisterEventHandler(OnProcessStart(target_action=ctrl, on_start=spawners + [eef])),
    ])
'''


TELEOP_LAUNCH = '''"""Gamepad teleop for the ZERO {key} workstation.

Generated by scripts/gen_bringup.py {key}. Edit the generator, not this file.

Run the sim first:   ros2 launch zero_bringup {key}.launch.py
Then this:           ros2 launch zero_bringup {key}_teleop.launch.py

Starts joy_node plus the teleop node. autorepeat_rate matters: without it joy_node only
publishes on change, so holding a stick steady stops the messages and the arm stops with them.
Set to match the teleop loop (50 Hz); at the default 20 it ran at 14.4 Hz with 100 ms gaps,
which the operator feels as sponginess.

  LB = drive left arm, RB = drive right arm (nothing held = frozen)
  left stick = X/Y     right stick = Z (up/down) + yaw (left/right)
  LT = left gripper, RT = right gripper (released open, pressed closed)
  A = return home      START = resync target to the measured pose

Check the axis map on a new pad with:  ros2 run zero_control joy_probe
"""

from launch import LaunchDescription
from launch.substitutions import PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


def generate_launch_description() -> LaunchDescription:
    bringup = FindPackageShare("zero_bringup")
    control = PathJoinSubstitution([bringup, "config", "{key}_control.yaml"])
    teleop = PathJoinSubstitution([bringup, "config", "teleop.yaml"])
    return LaunchDescription([
        Node(package="joy", executable="joy_node", output="screen",
             parameters=[{{"deadzone": 0.05, "autorepeat_rate": 50.0,
                           "coalesce_interval_ms": 5}}]),
        Node(package="zero_control", executable="teleop", output="screen",
             parameters=[control, teleop]),
    ])
'''


def control_yaml(key: str) -> str:
    """Params for zero_control's nodes, generated from the registry.

    The nodes must not import zero_layout: once installed, the repo's scripts/ dir is on no path.
    Emitting params keeps zero_layout as the single source of truth while letting them run
    identically from source or from an install tree.

    Two sections, and the split matters. The kinematic description (EEF frames, arm joint names,
    tool offset, gripper range) goes under the `/**` wildcard because it describes the robot, not
    any one node: eef_control, the teleop node and the dataset writer all need
    identical values, and a per-node copy is a divergence waiting to happen. Only the servo gains,
    genuinely eef_control's business, stay namespaced. Namespacing the frames instead makes every
    other node load with `left_eef_frame=""` and fail in the IK constructor.
    """
    r = L.ROBOTS[key]
    lines = [
        f"# Generated by scripts/gen_bringup.py {key}. Edit the generator, not this file.",
        "",
        "# Shared robot description. Every zero_control node reads these.",
        "/**:",
        "  ros__parameters:",
        f"    robot: {key}",
        f"    eef_offset: [{', '.join(f'{v}' for v in r['eef_offset'])}]",
        f"    eef_quat: [{', '.join(f'{v}' for v in r.get('eef_quat', (1.0, 0.0, 0.0, 0.0)))}]",
        f"    grip_range: [{r['grip_range'][0]}, {r['grip_range'][1]}]",
        f"    grip_ctrl_n: {len(r['grip_ctrl_joints'])}",
    ]
    # Task landmark positions, read from the compiled scene rather than restated here. The objects
    # rest where their measured geometry puts them, so a hand-written constant is a second source of
    # truth that goes stale the moment an asset or the table changes.
    mjcf = L.PKG / "mjcf" / f"zero_{key}.xml"
    if mjcf.exists():
        m = mujoco.MjModel.from_xml_path(str(mjcf))
        d = mujoco.MjData(m)
        mujoco.mj_resetDataKeyframe(m, d, mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_KEY, "home"))
        mujoco.mj_forward(m, d)

        def extent(body: str) -> tuple:
            """(origin, lowest, highest) z of a body's COLLISION geometry, from mesh vertices."""
            bid = mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_BODY, body)
            assert bid >= 0, f"{body} missing from {mjcf.name}"
            zlo, zhi = float("inf"), float("-inf")
            for g in range(m.body_geomadr[bid], m.body_geomadr[bid] + m.body_geomnum[bid]):
                if not (m.geom_contype[g] or m.geom_conaffinity[g]):
                    continue
                if m.geom_type[g] == mujoco.mjtGeom.mjGEOM_MESH:
                    mid = m.geom_dataid[g]
                    V = m.mesh_vert[m.mesh_vertadr[mid]:
                                    m.mesh_vertadr[mid] + m.mesh_vertnum[mid]].reshape(-1, 3)
                    W = (d.geom_xmat[g].reshape(3, 3) @ V.T).T + d.geom_xpos[g]
                    zlo, zhi = min(zlo, W[:, 2].min()), max(zhi, W[:, 2].max())
                elif m.geom_type[g] == mujoco.mjtGeom.mjGEOM_CYLINDER:
                    # size = (radius, half-length, unused); the half-length is index 1, not 2.
                    zlo = min(zlo, d.geom_xpos[g][2] - m.geom_size[g][1])
                    zhi = max(zhi, d.geom_xpos[g][2] + m.geom_size[g][1])
                else:
                    zlo = min(zlo, d.geom_xpos[g][2] - m.geom_size[g][2])
                    zhi = max(zhi, d.geom_xpos[g][2] + m.geom_size[g][2])
            return d.xpos[bid].copy(), zlo, zhi

        # The can is a primitive built by gen_scene, so its body is `obj_root`; the tray is still an
        # attached asset whose mesh sits on `plate_object`. Asserting the old `obj_object` name here made
        # this generator raise and leave the previous, now wrong, pick_xyz in place. Stale coordinates are
        # worse than a crash, so keep it fatal but look for the right body.
        obj_o, obj_lo, obj_hi = extent("obj_root")
        tray_o, tray_lo, tray_hi = extent("plate_object")

        # PICK: the object's own centre, which is where a gripper closes on it.
        lines.append("    pick_xyz: [" + ", ".join(f"{v:.5f}" for v in obj_o) + "]")

        # PLACE: not the tray's body origin. That origin sits ~3 mm above the table, i.e. inside the
        # tray, so servoing the gripper's pinch point to it drives through the tray floor. Physics stops
        # the arm ~48 mm short and it reads as an IK failure, and a kinematics-only reachability check
        # calls it reachable because ik.step knows nothing about collision. The release point is above
        # the rim, offset by half the carried object's height plus clearance.
        place_z = tray_hi + (obj_hi - obj_lo) / 2.0 + 0.010
        lines.append(f"    place_xyz: [{tray_o[0]:.5f}, {tray_o[1]:.5f}, {place_z:.5f}]")
        lines.append(f"    # tray rim top {tray_hi:.5f}, object height {obj_hi - obj_lo:.5f}")

        # Teleop workspace box, in table coordinates. A gamepad integrates velocity into a target pose,
        # so without a clamp the target keeps travelling after the arm has stopped: push into the table
        # for two seconds and the target is 20 cm underneath it, the IK residual is huge, and the arm no
        # longer answers the stick until you drive all the way back out. Bounds come from the table. The
        # z floor sits one object-height above the surface so the gripper can reach a resting object but
        # not through it.
        cx, cy = L.TABLE_CENTER_XY
        hx, hy, _ = L.TABLE_HALF
        lines += [
            f"    ws_min: [{cx - hx:.4f}, {cy - hy:.4f}, "
            f"{L.TABLE_TOP_Z + (obj_hi - obj_lo) / 2:.4f}]",
            f"    ws_max: [{cx + hx:.4f}, {cy + hy:.4f}, {L.TABLE_TOP_Z + 0.45:.4f}]",
        ]

    # Camera and F/T names for any node that wants to subscribe to all of them (the rerun viewer, the
    # dataset recorder). Generated so nobody maintains a second list.
    lines.append("    cameras: [" + ", ".join(f'"{c}"' for c in L.all_cameras()) + "]")
    lines.append("    ft_sensors: ["
                 + ", ".join(f'"{n}"' for n, _ in L.ft_sensors(key)) + "]")

    # Force in the tool frame, which is what makes force usable as a policy input. Each fingertip
    # sensor reports its wrench in its own site frame, and those frames differ between the two robots:
    # the reBot's finger frames are rotated 90 deg from its tool frame while Panda's first finger is
    # identity. So the raw per-finger vector is not the same physical measurement on both arms and
    # cannot be fed to a shared policy. Rotating each wrench into the tool frame and summing per hand
    # gives one quantity, one frame, one set of units, on both robots.
    #
    # The rotation is constant, since every gripper joint is prismatic so the fingers translate and
    # never rotate (0.00e+00 change between fully open and fully closed). Measured once here rather
    # than recomputed every frame.
    import numpy as _np
    rots, sides = [], []
    for sensor_name, _ in L.ft_sensors(key):
        side = "left" if sensor_name.startswith("left") else "right"
        eb = mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_BODY, L.prefixed(side, r["eef_body"]))
        sid = mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_SITE, f"{sensor_name}_site")
        assert eb >= 0 and sid >= 0, f"missing body/site for {sensor_name}"
        R = d.xmat[eb].reshape(3, 3).T @ d.site_xmat[sid].reshape(3, 3)
        rots += [float(v) for v in _np.asarray(R).reshape(-1)]
        sides.append(side)
    lines.append("    ft_rot: [" + ", ".join(f"{v:.6f}" for v in rots) + "]")
    lines.append("    ft_side: [" + ", ".join(f'"{s}"' for s in sides) + "]")
    lines.append(f"    grip_force: {r['grip_force']}")

    for side in L.SIDES:
        lines.append(f"    {side}_eef_frame: {r['urdf_eef_frame'].format(side=side)}")
        js = ", ".join(f'"{L.prefixed(side, j)}"' for j in r["arm_joints"])
        lines.append(f"    {side}_arm_joints: [{js}]")
        gs = ", ".join(L.prefixed(side, j) for j in r["gripper_joints"])
        lines.append(f"    {side}_grip_joints: [{gs}]")
        hs = ", ".join(f"{v}" for v in r["home"][side])
        lines.append(f"    {side}_home: [{hs}]")
    lines += [
        "",
        "# Servo gains, eef_control's own.",
        "zero_eef_control:",
        "  ros__parameters:",
        "    rate_hz: 100.0",
        "    damping: 0.05          # DLS lambda; reBot is 6-DoF so J is square and needs this",
        "    gain: 1.0",
        "    dq_max: 0.05           # rad per tick, bounds the step near singularities",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    key = sys.argv[1] if len(sys.argv) > 1 else "rebot"
    if key not in L.ROBOTS:
        raise SystemExit(f"unknown robot {key!r}")
    yaml_txt, names = controllers_yaml(key)
    (BRINGUP / "config").mkdir(parents=True, exist_ok=True)
    (BRINGUP / "launch").mkdir(parents=True, exist_ok=True)
    ycfg = BRINGUP / "config" / f"{key}_controllers.yaml"
    ycfg.write_text(yaml_txt)
    ccfg = BRINGUP / "config" / f"{key}_control.yaml"
    ccfg.write_text(control_yaml(key))
    tlp = BRINGUP / "launch" / f"{key}_teleop.launch.py"
    tlp.write_text(TELEOP_LAUNCH.format(key=key))
    lp = BRINGUP / "launch" / f"{key}.launch.py"
    lp.write_text(LAUNCH.format(key=key, controllers=["joint_state_broadcaster"] + names,
                                ncam=len(L.all_cameras()), cams=", ".join(L.all_cameras()),
                                ns=L.CAM_NS,
                                mjcf=str(L.PKG / "mjcf" / f"zero_{key}.xml"),
                                start_override=str(L.start_override_path(key)),
                                can_x=L.PICK_POS[0], can_y=L.PICK_POS[1]))
    print(f"[{key}] wrote {ycfg.name} ({len(names)} controllers) + {ccfg.name} + {lp.name}"
          f" + {tlp.name}")
    print(f"  controllers: {names}")


if __name__ == "__main__":
    main()
